#!/bin/bash
# Jamesblu DNSTT Termux Script Installer
#--------------------------------

rm -rf install

apt-get update
apt-get install -y dnsutils nano

wget --no-check-certificate -O ../usr/bin/menu https://raw.githubusercontent.com/hudaz4/Termux/main/James-script && chmod +x ../usr/bin/menu

echo "Installation Completed."
echo "James DNSTT Script v0.1.3"
echo
echo "James-script"
echo "type 'menu' to run the dnstt termux script"
